import React from "react";
// 1. Import your local images directly
import image1 from "../assets/1.jpg"; // Update path as needed
import image2 from "../assets/2.jpg";
import image3 from "../assets/3.png";
import image4 from "../assets/4.jpg";
import image5 from "../assets/5.jpg";
import image6 from "../assets/6.jpg";

function Latest() {
  const articles = [
    {
      id: 1,
      title: "The Future of Web Development",
      description:
        "Explore the rise of AI-driven tools, low-code platforms, and how they’re shaping the next generation of web applications.",
      category: "Technology",
      author: "A. Saam",
      date: "October 20, 2025",
      // 2. Use the imported image variable instead of the URL string
      image: image1,
    },
    {
      id: 2,
      title: "10 Essential Productivity Hacks",
      description:
        "Discover practical time management techniques to increase your focus, energy, and overall productivity.",
      category: "Lifestyle",
      author: "Sara Khan",
      date: "October 18, 2025",
      image: image2,
    },
    {
      id: 3,
      title: "Top 5 Programming Languages to Learn in 2025",
      description:
        "From Python to Rust — see which languages will dominate the software world in the upcoming years.",
      category: "Coding",
      author: "Bilal Ahmed",
      date: "October 16, 2025",
      image: image3,
    },
    {
      id: 4,
      title: "How to Build a Personal Portfolio Website",
      description:
        "A step-by-step guide to creating your own online portfolio using React, Tailwind, and Netlify.",
      category: "Design",
      author: "Fatima Noor",
      date: "October 10, 2025",
      image: image4,
    },
    {
      id: 5,
      title: "Cybersecurity Essentials for Developers",
      description:
        "Learn how to protect your applications from common vulnerabilities like XSS, CSRF, and SQL Injection.",
      category: "Security",
      author: "Ali Raza",
      date: "October 8, 2025",
      image: image5,
    },
    {
      id: 6,
      title: "Mastering Dark Mode UI Design",
      description:
        "Dark mode isn’t just a trend — it’s a design choice. Learn color contrast, readability, and accessibility best practices.",
      category: "UI/UX",
      author: "Hina Malik",
      date: "October 5, 2025",
      image: image6,
    },
  ];

  return (
    <section className="latest-section">
      <div className="container">
        <h2 className="section-title">📰 Latest Articles</h2>
        <p className="section-description">
          Explore trending posts from technology, lifestyle, and creative design fields.
        </p>

        <div className="post-grid">
          {articles.map((article) => (
            <article key={article.id} className="post-card">
              {/* 3. The `article.image` now holds the path generated by the import */}
              <img src={article.image} alt={article.title} className="post-image" />
              <div className="post-content">
                <span className="post-category">{article.category}</span>
                <h3 className="post-title">{article.title}</h3>
                <p className="post-description">{article.description}</p>
                <div className="post-meta">
                  <span>{article.author}</span> • <span>{article.date}</span>
                </div>
                <a href="#" className="read-more">Read More →</a>
              </div>
            </article>
          ))}
        </div>
      </div>
    </section>
  );
}

export default Latest;